eureka.client.fetch-registry=true

eureka.client.register-with-eureka=true


# spring.cloud.gateway.routes[0].id= HOSPITALMANAGEMENTSERVICE
# spring.cloud.gateway.routes[0].uri=lb://HOSPITALMANAGEMENTSERVICE
# spring.cloud.gateway.routes[0].predicates[0]=Path=/services/**


# spring.cloud.gateway.routes[1].id= HOSPITALMANAGEMENT
# spring.cloud.gateway.routes[1].uri=lb://HOSPITALMANAGEMENT
# spring.cloud.gateway.routes[1].predicates[0]=Path=/management/**
